title: Ludovico Bessi
logo: /assets/img/personal.png
email: ludovicobessi@gmail.com
description: ML engineer @Google
favicon: true
show_downloads: false
google_analytics: G-TQDGWRYGPQ
#google_analytics: UA-108144808-1
remote_theme: BDHU/minimalist
color-scheme: light
use_math: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

sidebar:
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/ludoro
  - name: Twitter
    icon: fa-brands fa-twitter
    link: https://twitter.com/bessi_ludovico
